// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvIjOKdnfzShAyzGYeKlhgIRDth8klaWQ',
    appId: '1:304044475305:web:46eff432a559d9fbc27ab8',
    messagingSenderId: '304044475305',
    projectId: 'maizemate-narasaraopet',
    authDomain: 'maizemate-narasaraopet.firebaseapp.com',
    storageBucket: 'maizemate-narasaraopet.firebasestorage.app',
    measurementId: 'G-095QT126X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1rwqV4G01Bplb9IfOAlYwHJ1OSBeCz4',
    appId: '1:304044475305:android:7c9f0c776b476956c27ab8',
    messagingSenderId: '304044475305',
    projectId: 'maizemate-narasaraopet',
    storageBucket: 'maizemate-narasaraopet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtX59vwmUxTi9OuPNkuC6uj3Y4eJNbNs',
    appId: '1:304044475305:ios:5f77af45b361ba79c27ab8',
    messagingSenderId: '304044475305',
    projectId: 'maizemate-narasaraopet',
    storageBucket: 'maizemate-narasaraopet.firebasestorage.app',
    iosBundleId: 'com.maizemate.appClean',
  );

}